# Generated by Django 5.2.5 on 2025-09-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SA2Fornecedor',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('a2_cod', models.CharField(db_column='A2_COD', max_length=20)),
                ('a2_nome', models.CharField(db_column='A2_NOME', max_length=255)),
                ('a2_cgc', models.CharField(db_column='A2_CGC', max_length=20)),
                ('a2_email', models.CharField(db_column='A2_EMAIL', max_length=255)),
                ('a2_end', models.CharField(db_column='A2_END', max_length=255)),
                ('a2_mun', models.CharField(db_column='A2_MUN', max_length=100)),
                ('a2_tel', models.CharField(db_column='A2_TEL', max_length=20)),
            ],
            options={
                'db_table': 'SA2010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC1',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('c1_filial', models.CharField(db_column='C1_FILIAL', max_length=10)),
                ('c1_num', models.CharField(db_column='C1_NUM', max_length=20)),
                ('c1_obs', models.CharField(blank=True, db_column='C1_OBS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SC1010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC7PedidoItem',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('c7_filial', models.CharField(db_column='C7_FILIAL', max_length=10)),
                ('c7_num', models.CharField(db_column='C7_NUM', max_length=20)),
                ('c7_item', models.CharField(db_column='C7_ITEM', max_length=4)),
                ('c7_produto', models.CharField(db_column='C7_PRODUTO', max_length=30)),
                ('c7_descri', models.CharField(db_column='C7_DESCRI', max_length=255)),
                ('c7_quant', models.DecimalField(db_column='C7_QUANT', decimal_places=2, max_digits=10)),
                ('c7_emissao', models.CharField(db_column='C7_EMISSAO', max_length=8)),
                ('c7_fornece', models.CharField(db_column='C7_FORNECE', max_length=20)),
                ('c7_encer', models.CharField(blank=True, db_column='C7_ENCER', max_length=1)),
                ('c7_conapro', models.CharField(blank=True, db_column='C7_CONAPRO', max_length=1, null=True)),
                ('c7_preco', models.DecimalField(db_column='C7_PRECO', decimal_places=2, max_digits=10)),
                ('c7_total', models.DecimalField(db_column='C7_TOTAL', decimal_places=2, max_digits=10)),
                ('c7_emitido', models.CharField(blank=True, db_column='C7_EMITIDO', max_length=1)),
                ('c7_tpfrete', models.CharField(blank=True, db_column='C7_TPFRETE', max_length=1)),
                ('c7_numsc', models.CharField(blank=True, db_column='C7_NUMSC', max_length=20)),
                ('c7_numcot', models.CharField(blank=True, db_column='C7_NUMCOT', max_length=20)),
                ('c7_compra', models.CharField(blank=True, db_column='C7_COMPRA', max_length=10)),
                ('c7_quje', models.DecimalField(db_column='C7_QUJE', decimal_places=2, default=0, max_digits=10)),
                ('c7_cond', models.CharField(blank=True, db_column='C7_COND', max_length=20, null=True)),
                ('c7_contato', models.CharField(blank=True, db_column='C7_CONTATO', max_length=50, null=True)),
                ('c7_datprf', models.CharField(blank=True, db_column='C7_DATPRF', max_length=8, null=True)),
                ('c7_ipi', models.DecimalField(db_column='C7_IPI', decimal_places=2, default=0, max_digits=10)),
                ('c7_frete', models.DecimalField(db_column='C7_FRETE', decimal_places=2, default=0, max_digits=10)),
                ('c7_vldesc', models.DecimalField(db_column='C7_VLDESC', decimal_places=2, default=0, max_digits=10)),
                ('c7_transp', models.CharField(blank=True, db_column='C7_TRANSP', max_length=20, null=True)),
                ('c7_local', models.CharField(blank=True, db_column='C7_LOCAL', max_length=10, null=True)),
                ('c7_um', models.CharField(blank=True, db_column='C7_UM', max_length=4, null=True)),
                ('c7_obs', models.CharField(blank=True, db_column='C7_OBS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SC7010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC8CotacaoItem',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('c8_filial', models.CharField(db_column='C8_FILIAL', max_length=10)),
                ('c8_num', models.CharField(db_column='C8_NUM', max_length=20)),
                ('c8_item', models.CharField(db_column='C8_ITEM', max_length=4)),
                ('c8_produto', models.CharField(db_column='C8_PRODUTO', max_length=30)),
                ('c8_quant', models.DecimalField(db_column='C8_QUANT', decimal_places=2, max_digits=10)),
                ('c8_um', models.CharField(db_column='C8_UM', max_length=4)),
                ('c8_preco', models.DecimalField(db_column='C8_PRECO', decimal_places=4, max_digits=10)),
                ('c8_total', models.DecimalField(db_column='C8_TOTAL', decimal_places=2, max_digits=10)),
                ('c8_fornece', models.CharField(db_column='C8_FORNECE', max_length=20)),
                ('c8_loja', models.CharField(db_column='C8_LOJA', max_length=4)),
                ('c8_contato', models.CharField(blank=True, db_column='C8_CONTATO', max_length=50, null=True)),
                ('c8_cond', models.CharField(blank=True, db_column='C8_COND', max_length=20, null=True)),
                ('c8_vldesc', models.DecimalField(db_column='C8_VLDESC', decimal_places=2, default=0, max_digits=10)),
                ('c8_valfre', models.DecimalField(db_column='C8_VALFRE', decimal_places=2, default=0, max_digits=10)),
                ('c8_seguro', models.DecimalField(db_column='C8_SEGURO', decimal_places=2, default=0, max_digits=10)),
                ('c8_despesa', models.DecimalField(db_column='C8_DESPESA', decimal_places=2, default=0, max_digits=10)),
                ('c8_valipi', models.DecimalField(db_column='C8_VALIPI', decimal_places=2, default=0, max_digits=10)),
                ('c8_valicm', models.DecimalField(db_column='C8_VALICM', decimal_places=2, default=0, max_digits=10)),
                ('c8_datprf', models.CharField(blank=True, db_column='C8_DATPRF', max_length=8, null=True)),
                ('c8_prazo', models.DecimalField(db_column='C8_PRAZO', decimal_places=0, default=0, max_digits=5)),
                ('c8_tpfrete', models.CharField(blank=True, db_column='C8_TPFRETE', max_length=2, null=True)),
                ('c8_obs', models.CharField(blank=True, db_column='C8_OBS', max_length=255, null=True)),
                ('c8_numsc', models.CharField(blank=True, db_column='C8_NUMSC', max_length=20, null=True)),
            ],
            options={
                'db_table': 'SC8010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SE4',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('e4_codigo', models.CharField(db_column='E4_CODIGO', max_length=20)),
                ('e4_descri', models.CharField(db_column='E4_DESCRI', max_length=255)),
            ],
            options={
                'db_table': 'SE4010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SYSCompany',
            fields=[
                ('m0_codfil', models.CharField(db_column='M0_CODFIL', max_length=10, primary_key=True, serialize=False)),
                ('m0_nome', models.CharField(db_column='M0_NOME', max_length=255)),
                ('m0_tel', models.CharField(blank=True, db_column='M0_TEL', max_length=20, null=True)),
                ('m0_cgc', models.CharField(db_column='M0_CGC', max_length=20)),
                ('m0_insc', models.CharField(blank=True, db_column='M0_INSC', max_length=20, null=True)),
                ('m0_endent', models.CharField(blank=True, db_column='M0_ENDENT', max_length=255, null=True)),
                ('m0_cident', models.CharField(blank=True, db_column='M0_CIDENT', max_length=100, null=True)),
                ('m0_bairent', models.CharField(blank=True, db_column='M0_BAIRENT', max_length=100, null=True)),
                ('m0_cepent', models.CharField(blank=True, db_column='M0_CEPENT', max_length=9, null=True)),
            ],
            options={
                'verbose_name': 'Informações da Empresa',
                'verbose_name_plural': 'Informações da Empresa',
                'db_table': 'SYS_COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FornecedorAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Local/Fornecedor')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor Avulso',
                'verbose_name_plural': 'Fornecedores Avulsos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('codigo_externo', models.CharField(blank=True, max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FornecedorUsuario',
            },
        ),
        migrations.CreateModel(
            name='FornecedorEmailAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail Adicional')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação (ex: e-mail de nota fiscal)')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_adicionais', to='portal.fornecedorusuario')),
            ],
            options={
                'verbose_name': 'E-mail Adicional',
                'verbose_name_plural': 'E-mails Adicionais',
            },
        ),
        migrations.CreateModel(
            name='ItemColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_disponibilidade', models.DateField()),
                ('data_agendada', models.DateField(blank=True, null=True)),
                ('status_coleta', models.CharField(choices=[('PENDENTE', 'Pendente de Agendamento'), ('AGENDADA', 'Coleta Agendada'), ('REALIZADA_OK', 'Realizada com Sucesso'), ('REALIZADA_DIVERGENCIA', 'Realizada com Divergência')], default='PENDENTE', max_length=50)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('chave_acesso_nfe', models.CharField(blank=True, max_length=44, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('observacao_coleta', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fornecedor_avulso', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_avulsa', models.TextField(blank=True, null=True)),
                ('ordem_visita', models.PositiveIntegerField(default=0, help_text='Ordem da visita na rota do dia')),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10)),
                ('agendado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_agendadas', to=settings.AUTH_USER_MODEL)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_conferidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ItemColeta',
                'ordering': ['ordem_visita', 'prioridade'],
            },
        ),
        migrations.CreateModel(
            name='ItemColetaDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_erp_recno', models.IntegerField()),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_coletada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao_divergencia', models.TextField(blank=True, null=True)),
                ('item_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='portal.itemcoleta')),
            ],
            options={
                'db_table': 'ItemColetaDetalhe',
            },
        ),
        migrations.CreateModel(
            name='PedidoLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateField()),
                ('status', models.CharField(choices=[('LIBERADO', 'Não Respondido'), ('PARCIALMENTE_DISPONIVEL', 'Parcialmente Disponível'), ('TOTALMENTE_DISPONIVEL', 'Totalmente Disponível'), ('COLETADO', 'Coletado')], default='LIBERADO', max_length=50)),
                ('data_liberacao_portal', models.DateTimeField(auto_now_add=True)),
                ('data_marcado_coleta', models.DateTimeField(blank=True, null=True)),
                ('observacao_fornecedor', models.TextField(blank=True, null=True)),
                ('fornecedor_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.fornecedorusuario')),
            ],
            options={
                'db_table': 'PedidoLiberado',
            },
        ),
        migrations.AddField(
            model_name='itemcoleta',
            name='pedido_liberado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='portal.pedidoliberado'),
        ),
    ]
