# Generated by Django 5.2.5 on 2025-08-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FornecedorAvulso',
        ),
    ]
