# Generated by Django 5.2.5 on 2025-08-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_fornecedoravulso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcoleta',
            options={'ordering': ['ordem_visita', 'prioridade']},
        ),
        migrations.AddField(
            model_name='itemcoleta',
            name='ordem_visita',
            field=models.PositiveIntegerField(default=0, help_text='Ordem da visita na rota do dia'),
        ),
        migrations.AddField(
            model_name='itemcoleta',
            name='prioridade',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10),
        ),
    ]
