# Generated by Django 5.2.5 on 2025-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_itemcoleta_options_itemcoleta_ordem_visita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SC1',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('c1_filial', models.CharField(db_column='C1_FILIAL', max_length=10)),
                ('c1_num', models.CharField(db_column='C1_NUM', max_length=20)),
                ('c1_obs', models.CharField(blank=True, db_column='C1_OBS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SC1010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC8CotacaoItem',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('c8_filial', models.CharField(db_column='C8_FILIAL', max_length=10)),
                ('c8_num', models.CharField(db_column='C8_NUM', max_length=20)),
                ('c8_item', models.CharField(db_column='C8_ITEM', max_length=4)),
                ('c8_produto', models.CharField(db_column='C8_PRODUTO', max_length=30)),
                ('c8_quant', models.DecimalField(db_column='C8_QUANT', decimal_places=2, max_digits=10)),
                ('c8_um', models.CharField(db_column='C8_UM', max_length=4)),
                ('c8_preco', models.DecimalField(db_column='C8_PRECO', decimal_places=4, max_digits=10)),
                ('c8_total', models.DecimalField(db_column='C8_TOTAL', decimal_places=2, max_digits=10)),
                ('c8_fornece', models.CharField(db_column='C8_FORNECE', max_length=20)),
                ('c8_loja', models.CharField(db_column='C8_LOJA', max_length=4)),
                ('c8_contato', models.CharField(blank=True, db_column='C8_CONTATO', max_length=50, null=True)),
                ('c8_cond', models.CharField(blank=True, db_column='C8_COND', max_length=20, null=True)),
                ('c8_vldesc', models.DecimalField(db_column='C8_VLDESC', decimal_places=2, default=0, max_digits=10)),
                ('c8_valfre', models.DecimalField(db_column='C8_VALFRE', decimal_places=2, default=0, max_digits=10)),
                ('c8_seguro', models.DecimalField(db_column='C8_SEGURO', decimal_places=2, default=0, max_digits=10)),
                ('c8_despesa', models.DecimalField(db_column='C8_DESPESA', decimal_places=2, default=0, max_digits=10)),
                ('c8_valipi', models.DecimalField(db_column='C8_VALIPI', decimal_places=2, default=0, max_digits=10)),
                ('c8_valicm', models.DecimalField(db_column='C8_VALICM', decimal_places=2, default=0, max_digits=10)),
                ('c8_datprf', models.CharField(blank=True, db_column='C8_DATPRF', max_length=8, null=True)),
                ('c8_prazo', models.DecimalField(db_column='C8_PRAZO', decimal_places=0, default=0, max_digits=5)),
                ('c8_tpfrete', models.CharField(blank=True, db_column='C8_TPFRETE', max_length=2, null=True)),
                ('c8_obs', models.CharField(blank=True, db_column='C8_OBS', max_length=255, null=True)),
                ('c8_numsc', models.CharField(blank=True, db_column='C8_NUMSC', max_length=20, null=True)),
            ],
            options={
                'db_table': 'SC8010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SE4',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('e4_cod', models.CharField(db_column='E4_COD', max_length=20)),
                ('e4_descri', models.CharField(db_column='E4_DESCRI', max_length=255)),
            ],
            options={
                'db_table': 'SE4010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SYSCompany',
            fields=[
                ('m0_codfil', models.CharField(db_column='M0_CODFIL', max_length=10, primary_key=True, serialize=False)),
                ('m0_nome', models.CharField(db_column='M0_NOME', max_length=255)),
                ('m0_tel', models.CharField(blank=True, db_column='M0_TEL', max_length=20, null=True)),
                ('m0_cgc', models.CharField(db_column='M0_CGC', max_length=20)),
                ('m0_insc', models.CharField(blank=True, db_column='M0_INSC', max_length=20, null=True)),
                ('m0_endent', models.CharField(blank=True, db_column='M0_ENDENT', max_length=255, null=True)),
                ('m0_cident', models.CharField(blank=True, db_column='M0_CIDENT', max_length=100, null=True)),
                ('m0_bairent', models.CharField(blank=True, db_column='M0_BAIRENT', max_length=100, null=True)),
                ('m0_cepent', models.CharField(blank=True, db_column='M0_CEPENT', max_length=9, null=True)),
            ],
            options={
                'verbose_name': 'Informações da Empresa',
                'verbose_name_plural': 'Informações da Empresa',
                'db_table': 'dbo.SYS_COMPANY',
                'managed': False,
            },
        ),
    ]
