# Generated by Django 5.2.5 on 2025-09-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_sc1_sc8cotacaoitem_se4_syscompany'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='syscompany',
            table='SYS_COMPANY',
        ),
        migrations.CreateModel(
            name='FornecedorEmailAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail Adicional')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação (ex: e-mail de nota fiscal)')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_adicionais', to='portal.fornecedorusuario')),
            ],
            options={
                'verbose_name': 'E-mail Adicional',
            },
        ),
    ]
