# Generated by Django 5.2.5 on 2025-09-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_syscompany_table_fornecedoremailadicional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedoremailadicional',
            options={'verbose_name': 'E-mail Adicional', 'verbose_name_plural': 'E-mails Adicionais'},
        ),
    ]
