# Generated by Django 5.2.5 on 2025-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_fornecedoremailadicional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoliberado',
            name='data_visualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
