# Generated by Django 5.2.5 on 2025-09-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_pedidoliberado_data_visualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SD1NFItem',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('d1_emissao', models.CharField(db_column='D1_EMISSAO', max_length=8)),
                ('d1_produto', models.CharField(db_column='D1_PRODUTO', max_length=30)),
                ('d1_vunit', models.DecimalField(db_column='D1_VUNIT', decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'SD1010',
                'managed': False,
            },
        ),
    ]
