# Generated by Django 5.2.5 on 2025-09-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_itemcoleta_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBM',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('bm_grupo', models.CharField(db_column='BM_GRUPO', max_length=4)),
                ('bm_desc', models.CharField(db_column='BM_DESC', max_length=100)),
            ],
            options={
                'db_table': 'SBM010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SCR010Aprovacao',
            fields=[
                ('recno', models.IntegerField(db_column='R_E_C_N_O_', primary_key=True, serialize=False)),
                ('cr_filial', models.CharField(db_column='CR_FILIAL', max_length=10)),
                ('cr_num', models.CharField(db_column='CR_NUM', max_length=20)),
                ('cr_user', models.CharField(db_column='CR_USER', max_length=20)),
                ('cr_status', models.CharField(db_column='CR_STATUS', max_length=2)),
            ],
            options={
                'db_table': 'SCR010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SYSUSR',
            fields=[
                ('usr_id', models.CharField(db_column='USR_ID', max_length=20, primary_key=True, serialize=False)),
                ('usr_nome', models.CharField(db_column='USR_NOME', max_length=255)),
            ],
            options={
                'db_table': 'SYS_USR',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='fornecedoravulso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedoremailadicional',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedorusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcoleta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemcoletadetalhe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidoliberado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fim', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='portal.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='PontoGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_gps', to='portal.rota')),
            ],
        ),
        migrations.CreateModel(
            name='EventoColeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('INICIO_COLETA', 'Início da Coleta'), ('FIM_COLETA', 'Fim da Coleta')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='portal.itemcoleta')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_coleta', to='portal.rota')),
            ],
        ),
    ]
