# Generated by Django 5.2.5 on 2025-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_motoristatoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontogps',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pontogps',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
