# Generated by Django 5.2.5 on 2025-09-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_sbm'), # Verifique se '0010_sbm' é sua última migração. Se não, ajuste.
    ]

    operations = [
        migrations.AddField(
            model_name='itemcoletadetalhe',
            name='motivo_divergencia',
            field=models.CharField(blank=True, choices=[('QUANTIDADE_A_MENOS', 'Divergência de quantidade (a menos)'), ('QUANTIDADE_A_MAIS', 'Divergência de quantidade (a mais)'), ('MERCADORIA_NAO_DISPONIBILIZADA', 'Mercadoria não disponibilizada'), ('NOTA_FISCAL_NAO_DISPONIBILIZADA', 'Nota fiscal não disponibilizada'), ('PRODUTO_AVARIADO', 'Produto avariado'), ('FALTA_DE_TEMPO', 'Não passou por falta de tempo'), ('INDISPONIBILIDADE_PRODUTO', 'Indisponibilidade do produto'), ('INDISPONIBILIDADE_VENDEDOR', 'Indisponibilidade do vendedor'), ('LOJA_FECHada', 'Loja fechada'), ('MUDANCA_ROTA', 'Mudança de rota'), ('OUTRO', 'Outro (especificar na observação)')], max_length=50, null=True, verbose_name='Motivo da Divergência'),
        ),
    ]